repos:
  - repo: local
    hooks:
      - id: pre-commit
        name: pre-commit
        entry: ./pre_commit.py
        language: system
        pass_filenames: false
        verbose: false
        stages: [commit]